const button = document.querySelector(".btn");
const quote = document.querySelector(".quote");
const container = document.querySelector(".container");


button.addEventListener("click", () => {
  quote.innerHTML = "Loading......";

  setTimeout(() => {
    let quotes = [
      "Believe you can and you’re halfway there. 🌟",
      "Your limitation—it’s only your imagination. 💭",
      "Push yourself, because no one else is going to do it for you. 💪",
      "Great things never come from comfort zones. 🚀",
      "Dream it. Wish it. Do it. ✨",
      "Success doesn’t just find you. You have to go out and get it. 🏆",
      "The harder you work for something, the greater you’ll feel when you achieve it. 🔥",
      "Don’t stop when you’re tired. Stop when you’re done. 🎯",
      "Wake up with determination. Go to bed with satisfaction. 😌",
      "Do something today that your future self will thank you for. 📈",
      "Little things make big days. 🌱",
      "It’s going to be hard, but hard does not mean impossible. ⚡",
      "Don’t wait for opportunity. Create it. 🛠️",
      "Sometimes we’re tested not to show our weaknesses, but to discover our strengths. 🦁",
      "Dream bigger. Do bigger. 🌍",
      "Push harder than yesterday if you want a different tomorrow. ⏭️",
      "If you get tired, learn to rest, not to quit. 🛌",
      "Stay positive, work hard, make it happen. 🙌",
      "Success is what comes after you stop making excuses. 🚫",
      "Doubt kills more dreams than failure ever will. 💡",
      "Discipline is the bridge between goals and accomplishments. 🌉",
      "Small progress each day adds up to big results. 📊",
      "Winners are not people who never fail, but people who never quit. 🏅",
      "Every day is a chance to get better. 🔄",
      "Don’t count the days, make the days count. ⏳",
      "Your only limit is your mind. 🧠",
      "Hard work beats talent when talent doesn’t work hard. 💯",
      "Stay hungry, stay foolish. 🍽️",
      "Opportunities don’t happen, you create them. 🔑",
      "Fall seven times and stand up eight. ⬆️",
      "Work hard in silence, let success make the noise. 🤫",
      "The best time to start was yesterday. The next best time is now. 🕒",
      "Your future is created by what you do today, not tomorrow. 📌",
      "Big journeys begin with small steps. 👣",
      "Don’t be afraid to give up the good to go for the great. 🦅",
      "Do it with passion or not at all. ❤️",
      "You are stronger than you think. 🐯",
      "Dreams don’t work unless you do. 🛠️",
      "Hustle until your haters ask if you’re hiring. 😎",
      "Be so good they can’t ignore you. 🎤",
      "Stay focused, stay humble, stay dedicated. 🧘",
      "Start where you are, use what you have, do what you can. 🎽",
      "Winners focus on winning, losers focus on winners. 🥇",
      "Make your life a masterpiece. 🎨",
      "Do one thing every day that scares you. 🕷️",
      "Turn your wounds into wisdom. 📚",
      "Action is the foundational key to success. 🔑",
      "Good things come to those who hustle. 💼",
      "Work until your idols become your rivals. 🐺",
      "Don’t wish for it, work for it. 🏋️",
      "Difficult roads often lead to beautiful destinations. 🏔️",
      "If you can dream it, you can do it. 🌌",
      "Prove yourself to yourself, not others. 🪞",
      "Great things never come easy. 🛤️",
      "Make each day your masterpiece. 🖌️",
      "Keep going, you are getting there. 🛣️",
      "Strength grows in the moments you think you can’t go on but keep going. 🌳",
      "Don’t stop until you’re proud. 🦾",
      "Be unstoppable. 🚀",
      "Hard days make you stronger. 🌪️",
      "Winners never quit and quitters never win. 🏆",
      "Every accomplishment starts with the decision to try. 🖋️",
      "Focus on the step in front of you, not the whole staircase. 🪜",
      "Do what you can with all you have. 🎯",
      "The secret of getting ahead is getting started. 🏁",
      "Your vibe attracts your tribe. 🤝",
      "Do not stop until you are proud. 🌟",
      "Turn “I can’t” into “I will.” 🔥",
      "Be stronger than your excuses. 🚫",
      "Life rewards persistence. ⏩",
      "Work for a cause, not for applause. 👏",
      "Do something great today. 🌞",
      "Success is built on persistence, not perfection. 🧱",
      "Your struggle today builds your strength tomorrow. 🏋️",
      "Start today, not someday. ⏰",
      "Courage is one step ahead of fear. 🦅",
      "The expert in anything was once a beginner. 📖",
      "Small steps in the right direction create a big difference. ➡️",
      "Chase goals, not people. 🏃",
      "Do it now, sometimes later becomes never. ⏳",
      "Stay patient and trust your journey. 🛤️",
      "If you believe it, you can achieve it. 🪂",
      "Your success story starts with you. 📖",
      "Hard times build strong people. 💪",
      "Consistency creates miracles. 🔄",
      "Your dreams are worth the effort. 🌙",
      "Don’t limit your challenges, challenge your limits. 🏔️",
      "Your effort today is your strength tomorrow. 🌞",
      "Winners train, losers complain. 🏋️",
      "Start small, think big. 🌱",
      "Work until you no longer have to introduce yourself. 🖐️",
      "It never gets easier, you just get better. 🏃",
      "Success is earned, not given. 💼",
      "Keep showing up. 📌",
      "The comeback is always stronger than the setback. 🔙",
      "Stop doubting yourself, work hard, and make it happen. ⚡",
      "Pain is temporary, pride is forever. 🦾",
      "Hustle in silence, let results speak. 📣",
      "Focus on your goals, not your fears. 🎯",
      "Create a life you can’t wait to wake up to. 🌅",
    ];

    let randomQuote = Math.floor(Math.random() * quotes.length);
    quote.innerHTML = quotes[randomQuote];
  }, 1000);
});
